spring:
  datasource:
    url: "jdbc:mysql://192.168.247.8:3306/universe"
    username: root
    password: ABC_abc1
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource

    #连接池配置
    dbcp2:
      initial-size: 50
      max-idle: 250
      min-idle: 50
      max-wait-millis: 10000
      validation-query: SELECT 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
debug: true
