server:
  port: 8080
spring:
  profiles:
    active: dev
  application:
    name:  springbootDemo
##设置字符编码
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

#  servlet:
#    context-path: /boot



